### ISSUE TITLE
grid-push and grid-push should support complex options for columns

### ISSUE THREAD

**Issue by whmii** [whmii/cask#14]
Similar to the `grid-column()` mixin, grid-push should allow a user to input custom local grid options like `grid-push(2 of 7)`.

https://github.com/whmii/cask/blob/master/app/assets/stylesheets/mixins/_grid-push.scss

**Comment by whmii** [comment]
So… I am very silly, and this is already a feature. hmmmm haha

**Comment by andrew-dash** [comment]
@whmii I can't seem to get `grid-push(x of x)` to work. It seems like `grid-push` needs to use a function similar to `grid-column-ratio`

Am I missing something? I am getting and undefined operation error at  `$_gutter-affordance: grid-settings(gutter) * $push;` in grid-push
